defaults: &defaults 

  # QuickSearch theme name
  #
  # To use a different theme, you must first add a new theme gem to the Gemfile,
  # run 'bundle install', then update this with the new theme name.
  #
  # See docs for more details: https://github.com/NCSU-Libraries/quick_search/blob/master/docs/configuration.md

  theme: 'grenander'

  # Searchers that QuickSearch will automatically search
  #
  # To use different searchers, you must first add the new searcher gem to the Gemfile,
  # run 'bundle install', then add the searcher name to this list. You must also
  # add a 'render_module()' helper call to your search results page tempate to expose the
  # results for that searcher.
  #
  # See docs for more details: https://github.com/NCSU-Libraries/quick_search/blob/master/docs/configuration.md

  searchers: [arclight,hyrax,history,mathes,pamphlets,books]

  # Searchers listed in the "result type guide" bar that lists result types that were found for a given search

  found_types: [arclight,hyrax]

  per_page: 5
  max_per_page: 50
  http_timeout: 3.5
  xhr_http_timeout: 15
# google_analytics_tracking_id: ""
  user: "stats"
  password: "statsSL356"

  on_campus:
    - !ruby/regexp '/^192\.(1|168)\.\d*\.\d*$/'


  common_searches: ["web of science", "google scholar", "refworks", "harvard business review", "pubmed", "ieee"]

  common_website_searches: ["dissertations", "exhibits", "textbooks", "visit the libraries", "government information", "literature review", "printing"]

  loaded_searches:
    - name: "ArchiveGrid"
      landing_page: "https://beta.worldcat.org/archivegrid/"
      query: "https://beta.worldcat.org/archivegrid/?p=1&q="
    - name: "WorldCat Archival Materials"
      landing_page: "https://www.worldcat.org/"
      query: "https://www.worldcat.org/search?fq=x0%3Aarchv&qt=advanced&dblist=638&q="

  loaded_website_searches:
    - name: "Books, Articles, Journals & More"
      landing_page: "http://search.lib.ncsu.edu"
      query: "http://search.lib.ncsu.edu/?q="

  doi_loaded_link: "http://doi.org/"

  best_bets:
    solr_url: "http://localhost:8983/solr/bestbets/select?"

development:
  <<: *defaults
#  realtime_url: http://path_to_websockets_server

test:
  <<: *defaults

staging:
  <<: *defaults
#  realtime_url: http://path_to_websockets_server
#  google_analytics_tracking_id: ""


production:
  <<: *defaults
#  realtime_url: http://path_to_websockets_server
  # Add or override config options here
